# https://megalinter.io/latest/supported-linters/
ADDITIONAL_EXCLUDED_DIRECTORIES:
  - vendor
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: "(vendor/)"
PROTOBUF_PROTOLINT_FILTER_REGEX_EXCLUDE: "(vendor/)"
ENABLE_LINTERS:
  - ACTION_ZIZMOR
  - ACTION_ACTIONLINT
  - ANSIBLE_ANSIBLE_LINT
  - BASH_SHELLCHECK
  - DOCKERFILE_HADOLINT
  - GO_GOLANGCI_LINT
  - MARKDOWN_MARKDOWNLINT
  - PYTHON_RUFF
  - PROTOBUF_PROTOLINT
  - REPOSITORY_BETTERLEAKS
  - REPOSITORY_KICS
  - YAML_YAMLLINT
REPOSITORY_KICS_ARGUMENTS: "--fail-on high"
